# backend:
#   name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
#   branch: master # Branch to update
#   repo: vagr9k/gatsby-material-starter # Repo for pushing new commits. Make sure to replace with your repo!
backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - {
              label: "Banner Images",
              name: "bannerImage",
              widget: "list",
              fields:
                [
                  { label: "ID", name: "id", widget: "number" },
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["internal", "external"],
                  },
                  {
                    label: "Link URL",
                    name: "linkURL",
                    widget: "string",
                    hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                  }
                ],
            }
          - { label: "Product Title", name: "productTitle", widget: "string", hint: "Tiêu đề của vùng Sản phẩm tiêu biểu" }
          - { label: "Product SubTitle", name: "productSubtitle", widget: "string", hint: "Tiêu đề con của vùng Sản phẩm tiêu biểu" }
          - { label: "Service Title", name: "serviceTitle", widget: "string", hint: "Tiêu đề của vùng Dịch vụ" }
          - { label: "Service SubTitle", name: "serviceSubtitle", widget: "string", hint: "Tiêu đề con của vùng Dịch vụ" }
          - { label: "Customer Title", name: "customerTitle", widget: "string", hint: "Tiêu đề của vùng Khách hàng" }
          - { 
              label: "Customers", 
              name: "customers", 
              widget: "list", 
              hint: "Các khách hàng tiêu biểu",
              fields: 
                [
                  { label: "ID", name: "id", widget: "number" },
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["internal", "external"],
                  },
                  {
                    label: "Link URL",
                    name: "linkURL",
                    widget: "string",
                    hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                  }
                ],
            }
          - { label: "Pricing Title", name: "pricingTitle", widget: "string", hint: "Tiêu đề của vùng Báo giá" }
          - { label: "Pricing Button", name: "pricingBtn", widget: "string", hint: "Nội dung button báo giá" }
          - { label: "Contact Title", name: "pricingTitle", widget: "string", hint: "Tiêu đề của vùng Liên Hệ" }
          - { label: "Contact SubTitle", name: "contactSSubtitle", widget: "string", hint: "Tiêu đề con của vùng Liên Hệ" }
          - { 
              label: "Office", 
              name: "offices", 
              widget: "list", 
              hint: "Các văn phòng",
              fields: 
                [
                  { label: "ID", name: "id", widget: "number" },
                  { label: "Office", name: "office", widget: "string"  },
                  { label: "Address", name: "address", widget: "string"  },
                  { label: "Phone", name: "phone", widget: "string" },
                  { label: "Fax", name: "fax", widget: "string" },
                  { label: "Hotline", name: "hotline", widget: "string" }
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "hainamer"
    label: "HaiNamer"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "hainamer" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string", hint: "Địa điểm/Thành phố"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "product"
    label: "Product"
    folder: "content/product"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "shortDesc", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: 
        - {label: "Phim", value: "film"}
        - {label: "Chương trình tin tức", value: "news"}
        - {label: "Gameshows", value: "gameshows"}
        - {label: "Chương trình xã hội", value: "social"}
        - {label: "Sản phẩm khác", value: "others"}
      }
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Hompage Position", name: "position", widget: "number", default: 1, valueType: "int", min: 1, max: 100}
  - name: "service"
    label: "Service"
    folder: "content/service"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Description", name: "shortDesc", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      # - {label: "Category", name: "category", widget: "select", options: ["Phim", "Chương trình tin tức", "Gameshows", "Chương trình xã hội", "Sản phẩm khác"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Hompage Position", name: "position", widget: "number", default: 1, valueType: "int", min: 1, max: 100}
  - name: "pricing"
    label: "Pricing"
    folder: "content/pricing"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing" }
      - {label: "Title", name: "title", widget: "string"}
      # - {label: "Short Description", name: "shortDesc", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: 
        - {label: "Báo điện tử", value: "e-news"}
        - {label: "Báo giấy", value: "newspaper"}
        - {label: "Truyền hình", value: "television"}
        - {label: "OOH", value: "ooh"}
      }
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Hompage Position", name: "position", widget: "number", default: 1, valueType: "int", min: 1, max: 100}
  